### ISSUE TITLE
Give the values of a column a Methadata like enum text

### ISSUE THREAD

**Issue by adorostkar** [jsonstat/jsonstat#1]
Hi all,
This is more of  a question than a bug. 
I have a jsonstat data structure where for one of the value columns in the table form I would like to place numbers from 0 to 3. Each number has a specific meaning. For instance 0=Neutral, 1=For, 2=Against . This is not a dimension so I can not give it an index and label.

Is there a way to attach metadata to one of the value columns. From the documentation I see that I can attach a status to each value but that is not exactly the best way. I know what values I would have in this column. I just don't want to place the names as the value.

If there is a better way, please give an example on how one can do it.

Thank you,
Best,
Ashkan

**Comment by badosa** [comment]
If I understand you correctly, these numbers from 0 to 3 are the content of the table cells (**value**): they are not a **dimension** or a **status** attached to the value.

You could use [note](https://json-stat.org/format/#note) if this is some sort of explanation but the best approach is probably to use [extension](https://json-stat.org/format/#extension) in a similar way how Eurostat is using it to attach a label to each of the status symbols. See for example

http://ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/en/tesem120?sex=T&precision=1&age=TOTAL&s_adj=NSA

**Comment by adorostkar** [comment]
Thank you for the answer,
From what I see in this example, what is used is a mix of status and extension, am I correct?

**Comment by badosa** [comment]
In this example (not necessarily your case), Eurostat is using extension to "explain" the meaning of the status codes. You can use extension in a similar manner to explain the codes used elsewhere.
