### ISSUE TITLE
JSON-Stat & API's

### ISSUE THREAD

**Issue by KoalaGeo** [jsonstat/jsonstat#3]
Hi, 

Do you know of any OS API implementations that offer JSON-Stat as an encoding?

Or is data generally getting served as a static file?

**Comment by badosa** [comment]
If by OS you mean the Ordnance Survey, no I'm not aware of any OS API that supports JSON-stat.

**Comment by KoalaGeo** [comment]
Sorry, no I meant open source. Like a nice fastapi docker image configured for JSON-Stat

**Comment by KoalaGeo** [comment]
Or do data publishers more usually just offer a static file? 

The datasets I'm thinking of are quite large (50+ years of global trade data) so was worried about performance

**Comment by badosa** [comment]
Sorry for the wrong answer (I would normally assume "OS" means "operating system" or "open source" but the "Geo" part in @KoalaGeo misled me). Unfortunately, the answer is still "no".
